# Generated by Django 5.2.12 on 2026-03-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('ward', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('dirty', 'Dirty'), ('occupied', 'Occupied')], default='clean', max_length=10)),
            ],
        ),
    ]
