# Generated by Django 5.2.12 on 2026-03-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], default='green', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_treatment', 'In Treatment'), ('discharged', 'Discharged')], default='waiting', max_length=20)),
                ('department', models.CharField(default='General', max_length=50)),
                ('wait_time', models.IntegerField(default=0)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
