# Generated by Django 5.2.12 on 2026-03-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('queue_count', models.IntegerField(default=0)),
                ('avg_wait_time', models.IntegerField(default=0)),
                ('status', models.CharField(default='normal', max_length=20)),
            ],
        ),
    ]
